#ifndef PHANTOMJS_GLOBAL_H
#define PHANTOMJS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHANTOMJS_LIBRARY)
#  define PHANTOMJS_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHANTOMJS_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHANTOMJS_GLOBAL_H
